name: mindset
dependencies:
  - python
  - pip:
    - brainflow
    - pylsl
    - pyxdf
    - numpy
    - mne
    - matplotlib
    - scipy
    - PyQt5
    - joblib
    - notebook
    - sklearn
    - pyriemann
    - seaborn
    - pyyaml